### ISSUE TITLE
Java version required for PoCoTo

### ISSUE THREAD

**Issue by jbarth-ubhd** [cisocrgroup/PoCoTo#13]
PoCoTo is based on netbeans, from approx. 2014

To my experience, newer java releases do not work with PoCoTo.
 * Oracle Java 7u80 does not allow »Check for Updates« (possibly TLS version?)
 * Oracle Java 8u5 seems to work
 * openjdk-8-jre version 8u222-b10-1ubuntu1~18.04.1 seems to work, too [line added 2019-08-09]
 * newer java versions (Oracle, openjdk) (~-8-~ 9 ... 12) do not work

**Comment by michaelsjackson** [comment]
What is the point of having such an application working only with some magical java versions?
